name: Update Playlist Cookies

on:
  workflow_dispatch:

  schedule:
    - cron: "*/40 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Updater
        env:
          SOURCE_URL: ${{ secrets.SOURCE_URL }}
        run: python scripts/update.py

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add playlist.m3u

          git diff --cached --quiet || git commit -m "Auto update cookies"

          git push
